version: "3"

services:
    databasesql:
      image: mysql:latest
      restart: always
      ports:
      - "3306:3306"
      volumes:
        - ~src/db/init:/docker-entrypoint-initdb.d
        - ~src/db/data:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: clipsproject
        MYSQL_DATABASE: PHPCLIPS
    adminer:
      image: adminer:latest
      restart: always
      ports:
      - 8080:8080
